background = 0xFFEFF1F5
base = 0xFFE6E9EF
text = 0xFF4C4F69
alternate_base = 0xFFCCD0DA
bright_text = 0xFF4C4F69
accent = 0xFF1E66F5
link_text = 0xFF1E66F5
accent_secondary = 0xFF7287FD
font_family = "IBM Plex Mono"
font_family_monospace = "monospace"
font_size = 13
small_font_size = 10
rounding_large = 0
rounding_small = 0
