# theme: catppuccin-latte-float
background              #EFF1F5
foreground              #4C4F69
cursor                  #4C4F69
cursor_text_color       #EFF1F5
selection_foreground    #4C4F69
selection_background    #ACB0BE
active_tab_background   #E6E9EF
active_tab_foreground   #4C4F69
inactive_tab_background #E6E9EF
inactive_tab_foreground #6C6F85

background_opacity 0.90
