# theme: catppuccin-latte
background              #EFF1F5
foreground              #4C4F69
cursor                  #4C4F69
cursor_text_color       #EFF1F5
selection_foreground    #4C4F69
selection_background    #ACB0BE
active_tab_background   #E6E9EF
active_tab_foreground   #4C4F69
inactive_tab_background #E6E9EF
inactive_tab_foreground #6C6F85

background_opacity 0.90

color0  #5C5F77
color1  #D20F39
color2  #40A02B
color3  #DF8E1D
color4  #1E66F5
color5  #EA76CB
color6  #04A5E5
color7  #EFF1F5
color8  #6C6F85
color9  #E64553
color10 #40A02B
color11 #FE640B
color12 #7287FD
color13 #8839EF
color14 #209FB5
color15 #FFFFFF
